soul_connection_dashboard/admin_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "admin_app"

urlpatterns = [
    path('login/', views.login_employee, name='login'),
    path('logout/', views.logout_employee, name='logout'),
    path('dash/', views.acceuil, name='dash'),  # Page d'accueil
    #path('customer/<int:customer_id>/', views.customer_details, name='customer_details'),
]

soul_connection_dashboard/coach/urls.py
from django.urls import path
from .views import list_employees
from . import views

app_name = "coachs"

urlpatterns = [
    path('list/', views.list_employees, name='coach'),
    path('create/', views.create_employee, name='coach-create'),
    path('detail/<int:id>/', views.detail_employee, name='coach-detail'),
    path('detail/<int:id>/message', views.create_message, name='message-create'),
    path('detail/<int:id>/messages/list', views.list_messages, name='message-list'),
    path('update/<int:id>/', views.update_employee, name='coach-update'),
    path('delete/<int:id>/', views.delete_employee, name='coach-delete'),
    #path('customer/<int:customer_id>/', views.customer_details, name='customer_details'),
]

soul_connection_dashboard/customer/urls.py
from django.urls import path
from .views import list_customers
from . import views

app_name = "customers"

urlpatterns = [
    path('list/', views.list_customers, name='customer'),
    path('compatibility/', views.customers_compatibility, name='compatibility'),
    path('create/', views.create_customers, name='customer-create'),
    path('detail/<int:id>/', views.detail_customers, name='customer-detail'),
    path('<int:id>/clothes/', views.customers_clothes, name='customer-clothes'),
    path('update/<int:id>/', views.update_customers, name='customer-update'),
    path('delete/<int:id>/', views.delete_customers, name='customer-delete'),
    path('<int:id>/clothes/create_clothes/', views.create_clothe, name='customer-create-clothes'),
    path('<int:customer_id>/clothes/update_clothes/<int:id>/', views.update_clothe, name='customer-update-clothes'),
    path('<int:customer_id>/clothes/delete_clothes/<int:id>', views.delete_clothe, name='customer-delete-clothes'),
]

soul_connection_dashboard/events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
      path('list/', views.list_event, name='event-list'),
      path('create_event/', views.create_events, name='event-create'),
      path('update_event/<int:id>/', views.update_events, name='update-event'),
      # path('delete_event/<int:id>/', views.delete_events, name='delete-event'),
]

soul_connection_dashboard/soul_connection_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from admin_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employees/', include("admin_app.urls", namespace="admin_app")),
    path('coachs/', include("coach.urls", namespace="coachs")), 
    path('customers/', include("customer.urls", namespace="customers")),
    path('encounters/', include("encounters.urls", namespace="encounters")),
    path('tips/', include("tips.urls", namespace="tips")),
    path('events/', include("events.urls", namespace="events")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

soul_connection_dashboard/tips/urls.py
from django.urls import path
from . import views

app_name = "tips"

urlpatterns = [
     path('list/', views.list_tips, name='tips-list'),
]

soul_connection_dashboard/customer/models.py
from django.db import models
from coach.models import Employee

class Customer(models.Model):
    def __str__(self):
        return f'{self.name}'
    id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, unique=True)
    birth_date = models.CharField(max_length=1000, blank=True)
    gender = models.CharField(max_length=100)
    description = models.TextField(max_length=5000, blank=True)
    astrological_sign = models.CharField(max_length=100)
    address = models.CharField(max_length=100, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    image = models.ImageField(upload_to='customer_images/')
    coach = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, related_name='clients', blank=True)


class Payment(models.Model):
    def __str__(self):
        return f'{self.customer} - {self.date} - {self.amount}'
    id = models.IntegerField(unique=True, primary_key=True)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    date = models.CharField(max_length=1000, blank=True)
    payment_method = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    comment = models.CharField(max_length=100)

class Clothe(models.Model):
    def __str__(self):
        return f'{self.customer} - {self.id} - {self.type}'
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    id = models.IntegerField(unique=True, primary_key=True)
    type = models.CharField(max_length=200, blank=False)
    image = models.ImageField(upload_to='customer_clothes_images/')

soul_connection_dashboard/customer/forms.py
from django import forms
from .models import Customer, Clothe, Payment
from coach.models import Employee

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"
    
    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        self.fields['coach'].queryset = Employee.objects.filter(work="Coach")

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = "__all__"

class CompatibilityForm(forms.Form):
    first_client = forms.EmailField(label='Email', required=True)
    second_client = forms.EmailField(label='Email', required=True)

class ClothingForm(forms.Form):
    my_id = forms.IntegerField()
    id_clothes = forms.IntegerField()
    type = forms.CharField(max_length=200)
    image = forms.ImageField()

class ClothingItemForm(forms.ModelForm):
    class Meta:
        model = Clothe
        fields = "__all__"

soul_connection_dashboard/customer/views.py
# Create your views here.
from django.db.models.fields import return_None
from django.shortcuts import render, get_object_or_404
from .models import Customer, Clothe, Payment
from encounters.models import Encounter
from .forms import CustomerForm, CompatibilityForm, ClothingItemForm
from admin_app.models import Meeting
from datetime import datetime
from django.shortcuts import redirect
from .astro import check_client_compatibility
from django.contrib.auth.decorators import login_required

@login_required(login_url='/employees/login/')
def create_customers(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('customers:customer-detail', id=form.instance.id)
        else:
             print("Les erreurs :", form.errors)
    else:
        form = CustomerForm()
    return render(request,
                  'customer/create_customers.html',
                  {'form': form})

@login_required(login_url='/employees/login/')
def list_customers(request):
    customers = Customer.objects.all()
    if request.method == "GET":
        name = request.GET.get('name')
        surname = request.GET.get('surname')
        if name or surname:
            customers = Customer.objects.filter(name=name, surname=surname)
    payment = []
    for i in customers:
        payment.append(i.payment_set.all())
    return render(request,'customer/list_customers.html',{'customers': customers,'payment': payment})

@login_required(login_url='/employees/login/')
def detail_customers(request, id):
    customers = Customer.objects.get(id=id)
    payment = customers.payment_set.all()
    meetings = customers.encounters.all()
    positives = 0; progess = 0
    for i in meetings:
        if i.rating >= 4:
            positives += 1
        else:
            progess += 1
    def sorte_date(meetings):
        try:
            return datetime.strptime(meetings.date, "%Y-%m-%d")
        except ValueError:
            return None
    meetings = sorted(meetings, key=sorte_date, reverse=True)
    return render(request,
                  'customer/detail_customers.html',
                  {'customers': customers,
                   'payment': payment,
                   'meetings': meetings,
                   'positives': positives,
                   'progess': progess,
                   })

@login_required(login_url='/employees/login/')
def update_customers(request, id):
    customers = Customer.objects.get(id=id)
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customers)
        if form.is_valid():
            customers = form.save()
            return redirect('customers:customer-detail', id=customers.id)
    else:
        form = CustomerForm(instance=customers)
    return render(request,
                  'customer/update_customers.html',
                  {'form': form, 'customers': customers})

@login_required(login_url='/employees/login/')
def delete_customers(request, id):
    customers = Customer.objects.get(id=id)
    if request.method == 'POST':
        if customers.image:
            customers.image.delete()
        customers.delete()
        return redirect('customers:customer')
    return render(request,
                  'customer/delete_customers.html',
                  {'customers': customers})

@login_required(login_url='/employees/login/')
def customers_compatibility(request):
    percentage = 0
    if request.method == 'POST':
        form_log = CompatibilityForm(request.POST)
        if form_log.is_valid():
            first_client = form_log.cleaned_data['first_client']
            second_client = form_log.cleaned_data['second_client']
            info_first_client = Customer.objects.get(email=first_client)
            info_second_client = Customer.objects.get(email=second_client)
            percentage = check_client_compatibility(info_first_client.astrological_sign, info_second_client.astrological_sign)
            print("email : ", info_first_client.email, "astrological_sign : ", info_first_client.astrological_sign)
            print("email : ", info_second_client.email, "astrological_sign : ", info_second_client.astrological_sign)
            print("percentage : ", percentage)
    else:
        form_log = CompatibilityForm()
    context = {'form_log': form_log, 'percentage': percentage}
    return render(request, 'customer/compatibility.html', context)

@login_required(login_url='/employees/login/')
def customers_clothes(request, id):
    customer = Customer.objects.get(id=id)
    clothe = customer.clothe_set.all()
    if request.method == "POST":
        ids = request.POST.get('ids')
        if ids:
            id_list = [int(i.strip()) for i in ids.split(',')]
            clothe = clothe.filter(id__in=id_list)
    return render(request, 'customer/customers_clothes.html', {'customer': customer, 'clothe': clothe})

@login_required(login_url='/employees/login/')
def create_clothe(request, id):
    if request.method == 'POST':
        form = ClothingItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('customers:customer-clothes', id=id)
        else:
             print("Les erreurs :", form.errors)
    else:
        form = ClothingItemForm()
    return render(request,'customer/create_clothes.html',{'form': form})

@login_required(login_url='/employees/login/')
def update_clothe(request, customer_id, id):
    cloth = Clothe.objects.get(id=id)
    if request.method == 'POST':
        form = ClothingItemForm(request.POST, request.FILES, instance=cloth)
        if form.is_valid():
            cloth = form.save()
            return redirect('customers:customer-clothes', id=customer_id)
    else:
        form = ClothingItemForm(instance=cloth)
    return render(request,'customer/update_clothes.html',{'form': form, 'cloth': cloth})

@login_required(login_url='/employees/login/')
def delete_clothe(request, customer_id, id):
    cloth = Clothe.objects.get(id=id)
    if request.method == 'POST':
        if cloth.image:
            cloth.image.delete()
        cloth.delete()
        return redirect('customers:customer-clothes', id=customer_id)
    return render(request, 'customer/delete_clothe.html', {'cloth': cloth})

soul_connection_dashboard/customer/templates/customer/compatibility.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Client Compatibility</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <style>
        /* General Reset */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f8f9fa;
            color: #333;
        }

        /* Navbar Styling */
        .navbar {
            background-color: #fff;
            padding: 15px 30px;
            border-bottom: 2px solid #eee;
            display: flex;
            align-items: center;
            justify-content: space-between;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
        }

        .navbar .logo {
            font-size: 24px;
            font-weight: 600;
            color: #007bff;
        }

        .navbar a {
            text-decoration: none;
            color: #555;
            margin-right: 25px;
            font-weight: 500;
            transition: color 0.3s ease;
        }

        .navbar a.active {
            color: #007bff;
            border-bottom: 2px solid #007bff;
        }

        .navbar a:hover {
            color: #007bff;
        }

        .navbar .right-icons {
            display: flex;
            align-items: center;
        }

        .navbar .icon {
            margin-left: 20px;
            font-size: 20px;
            cursor: pointer;
        }

        /* Container Styles */
        .container {
            max-width: 700px;
            background-color: #fff;
            border-radius: 10px;
            padding: 40px;
            margin: 100px auto;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            font-size: 28px;
            margin-bottom: 30px;
            color: #007bff;
        }

        /* Formulaire Styles */
        .selectors {
            display: flex;
            justify-content: space-between;
            margin-bottom: 25px;
        }

        .selectors div {
            width: 48%;
        }

        label {
            font-weight: 600;
            color: #333;
            margin-bottom: 5px;
            display: block;
        }

        select {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ddd;
            border-radius: 5px;
            background-color: #f9f9f9;
            transition: all 0.3s ease;
        }

        select:focus {
            border-color: #007bff;
            outline: none;
            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
        }

        button {
            background-color: #007bff;
            color: #fff;
            padding: 12px 30px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #0056b3;
        }

        .result {
            margin-top: 30px;
            font-size: 22px;
            text-align: center;
            font-weight: 600;
            color: #28a745;
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            .selectors {
                flex-direction: column;
            }

            .selectors div {
                width: 100%;
                margin-bottom: 20px;
            }
        }
    </style>
</head>
<body>

    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}">Coaches</a>
            <a href="{% url 'customers:customer' %}">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}">Events</a>
            <a href="{% url 'customers:compatibility' %}" class="active">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="icon">🌍</div>
            <div class="icon">👤</div>
        </div>
    </div>

    <div class="container">
        <h1>Check Compatibility Between Clients</h1>

        <form id="compatibilityForm" action="" method="post">
            {% csrf_token %}
            <div class="selectors">
                <div>
                    <label for="client1">First Client:</label>
                    {{ form_log.first_client }}
                </div>
                <div>
                    <label for="client2">Second Client:</label>
                    {{ form_log.second_client }}
                </div>
            </div>

            <button type="submit">Calculate Compatibility</button>
        </form>

        <div class="result" id="compatibilityResult">
            Compatibility Percentage: {{ percentage }}%
        </div>
    </div>

</body>
</html>

soul_connection_dashboard/customer/templates/customer/customers_clothes.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vêtement du client</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_vete.css' %}">
</head>
<body>
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}">Coaches</a>
            <a href="{% url 'customers:customer' %}"class="active">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>

    <div class="header">
        <button type="button" id="cancelDelete" class="back-button"><span>&larr;</span>Back</button>
        <a href="{% url 'customers:customer-create-clothes' customer.id %}">
            <button class="add-button">Add+</button>
        </a>
    </div>

    <div class="form-box">
        <h1>Clothing combination</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="ids">Enter the clothes ids :</label>
            <input type="text" id="ids" name="ids" placeholder="Exemple: 1, 2, 3" required>
            <button type="submit">Display</button>
        </form>
    </div>
    <h1>Clothes of {{ customer.name }}</h1>

    <div class="clothing-container">
        {% if clothe %}
            {% for item in clothe %}
                <div class="clothing-item">
                    <h2>{{ item.type }} {{ item.id }}</h2>
                    <a href="{% url 'customers:customer-update-clothes' customer.id item.id %}">
                    <img src="{{ item.image.url }}" alt="">
                        <a href="{% url 'customers:customer-delete-clothes' customer.id item.id %}">
                            <input type="button" class="delete-button" value="Delete">
                        </a>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <p>No clothes corresponds to this ids</p>
        {% endif %}
    </div>

    <script>
        // Gestion du bouton "Annuler"
        document.getElementById("cancelDelete").onclick = function () {
            history.back();
        }
    </script>
</body>
</html>

soul_connection_dashboard/customer/templates/customer/delete_customers.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Suppression d'utilisateur</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_delete_cus.css' %}">
</head>

<body>
    {% block content %}
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}">Coaches</a>
            <a href="{% url 'customers:customer' %}" class="active">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>

    <button class="back-button" onclick="history.back()">Back</button>

    <div class="container home">
        <div class="confirmation-box">
            <p>Do you really want to delete {{customers.name}} {{customers.surname}} ?</p>
            <form method="POST" action="{% url 'customers:customer-delete' customers.id %}">
                {% csrf_token %}
                <button type="submit" class="confirm-button">Confirm</button>
                <button type="button" id="cancelDelete" class="cancel-button">Cancel</button>
            </form>

            <div class="delete-message" id="deleteMessage" style="display: none;">This user has been deleted.</div>
        </div>
    </div>

    <script>
        // Gestion du bouton "Annuler"
        document.getElementById("cancelDelete").onclick = function () {
            history.back();
        }

        // Simuler un message de confirmation de suppression si le formulaire est soumis
        document.querySelector("form").onsubmit = function (event) {
            event.preventDefault(); // Bloquer la soumission par défaut pour la démonstration

            // Simuler la suppression
            var deleteMessage = document.getElementById("deleteMessage");
            deleteMessage.style.display = "block";

            // Simuler une redirection après suppression (à remplacer par la logique Django si nécessaire)
            setTimeout(function () {
                event.target.submit(); // Soumission réelle du formulaire après un délai de 2 secondes
            }, 2000);
        }
    </script>

    {% endblock %}
</body>
</html>

soul_connection_dashboard/customer/templates/customer/detail_customers.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer details</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_det_custo.css' %}">
</head>
<body>
    {% block content %}
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}">Coaches</a>
            <a href="{% url 'customers:customer' %}"class="active">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>
    <!-- Header with Title and Back Button -->
    <div class="header">
        <h1>Customer Details</h1>
        <button type="button" id="cancelDelete" class="back-button"><span>&larr;</span>Back</button>
    </div>
    <div class="container">
        <!-- Left Pane -->
        <div class="left-pane-box">
            <div class="left-pane">
                <div class="user-info">
                    <img src="{{ customers.image.url }}" alt="User Photo">
                    <h2>{{ customers.name }} {{ customers.surname }}</h2>
                </div>
                <!-- <div class="icon-container">
                    <p class="email-icon"><i class="fas fa-envelope"></i></p>
                    <p class="favorite-icon">
                        <img src="{% static 'images/favori.png' %}" alt="Favorite" class="favorite-img">
                    </p>
                </div> -->
                <div class="table-container-user">
                    <table>
                        <tr>
                            <th>{{ meetings | length }}</th>
                            <th>{{ positives }}</th>
                            <th>{{ progess }}</th>
                        </tr>
                        <tr>
                            <td>Total <br> Encounters</td>
                            <td>Positives</td>
                            <td>In progress</td>
                        </tr>
                    </table>
                </div>
                <div class="short-details">
                    <div class="detail-item">
                        <strong>User ID</strong>
                        <p>{{ customers.id }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Email</strong>
                        <p>{{ customers.email }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Description</strong>
                        <p>{{ customers.description }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Address</strong>
                        <p>{{ customers.address }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Last Activity</strong>
                        <p>{{ customers.last_login }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Coach</strong>
                        <p>{{ customers.coach.name }} {{ customers.coach.surname }}</p>
                    </div>
                    <div class="action-buttons">
                        <a href="{% url 'customers:customer-clothes' customers.id %}" class="vet-button">Client Clothes</a>
                        <a href="{% url 'customers:customer-update' customers.id %}" class="edit-button">Edit</a>
                        <a href="{% url 'customers:customer-delete' customers.id %}" class="delete-button">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    
        <!-- Right Pane (Tables) -->
        <div class="right-pane">
            <div class="table-container">
                <h3>Recent Meetings</h3>
                <table class="meeting-table">
                    <tr>
                        <th>Date</th>
                        <th>Rating</th>
                        <th>Report</th>
                        <th>Source</th>
                    </tr>
                    {% for meeting in meetings %}
                    <tr>
                        <td>{{ meeting.date }}</td>
                        <td class="stars">
                            <!-- Loop to display filled and empty stars based on the rating -->
                            {% for i in "12345" %}
                                {% if i <= meeting.rating %}
                                    <span class="star filled">&#9733;</span> <!-- Filled star for the rating -->
                                {% else %}
                                    <span class="star empty">&#9733;</span> <!-- Empty star for the remaining -->
                                {% endif %}
                            {% endfor %}
                        </td>                        
                        <td>{{ meeting.comment }}</td>
                        <td class="source {% cycle 'source-yellow' 'source-green' 'source-blue' %}">
                            {{ meeting.source }}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
    
            <div class="table-container">
                <h3>Payment History</h3>
                <table class="payment-table">
                    <tr>
                        <th>Date</th>
                        <th>Payment Method</th>
                        <th>Amount</th>
                        <th>Comment</th>
                    </tr>
                    {% for pay in payment %}
                    <tr>
                        <td>{{ pay.date }}</td>
                        <td>
                            {% if pay.payment_method == 'Bank Transfer' %}
                                <img src="{% static 'images/visa.png' %}" alt="Bank Transfer" class="payment-icon">
                            {% elif pay.payment_method == 'Credit Card' %}
                                <img src="{% static 'images/mastercard.png' %}" alt="Credit Card" class="payment-icon">
                            {% elif pay.payment_method == 'PayPal' %}
                                <img src="{% static 'images/paypal.png' %}" alt="PayPal" class="payment-icon">
                            {% else %}
                                {{ pay.payment_method }}
                            {% endif %}
                        </td>
                        <td class="amount">${{ pay.amount }}</td>
                        <td>{{ pay.comment }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

    <script>
        document.getElementById("cancelDelete").onclick = function () {
            history.back();
        }
    </script>
    {% endblock %}
</body>
</html>