soul_connection_dashboard/admin_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "admin_app"

urlpatterns = [
    path('login/', views.login_employee, name='login'),
    path('logout/', views.logout_employee, name='logout'),
    path('dash/', views.acceuil, name='dash'),  # Page d'accueil
    #path('customer/<int:customer_id>/', views.customer_details, name='customer_details'),
]

soul_connection_dashboard/coach/urls.py
from django.urls import path
from .views import list_employees
from . import views

app_name = "coachs"

urlpatterns = [
    path('list/', views.list_employees, name='coach'),
    path('create/', views.create_employee, name='coach-create'),
    path('detail/<int:id>/', views.detail_employee, name='coach-detail'),
    path('detail/<int:id>/message', views.create_message, name='message-create'),
    path('detail/<int:id>/messages/list', views.list_messages, name='message-list'),
    path('update/<int:id>/', views.update_employee, name='coach-update'),
    path('delete/<int:id>/', views.delete_employee, name='coach-delete'),
    #path('customer/<int:customer_id>/', views.customer_details, name='customer_details'),
]

soul_connection_dashboard/customer/urls.py
from django.urls import path
from .views import list_customers
from . import views

app_name = "customers"

urlpatterns = [
    path('list/', views.list_customers, name='customer'),
    path('compatibility/', views.customers_compatibility, name='compatibility'),
    path('create/', views.create_customers, name='customer-create'),
    path('detail/<int:id>/', views.detail_customers, name='customer-detail'),
    path('<int:id>/clothes/', views.customers_clothes, name='customer-clothes'),
    path('update/<int:id>/', views.update_customers, name='customer-update'),
    path('delete/<int:id>/', views.delete_customers, name='customer-delete'),
    path('<int:id>/clothes/create_clothes/', views.create_clothe, name='customer-create-clothes'),
    path('<int:customer_id>/clothes/update_clothes/<int:id>/', views.update_clothe, name='customer-update-clothes'),
    path('<int:customer_id>/clothes/delete_clothes/<int:id>', views.delete_clothe, name='customer-delete-clothes'),
]

soul_connection_dashboard/events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
      path('list/', views.list_event, name='event-list'),
      path('create_event/', views.create_events, name='event-create'),
      path('update_event/<int:id>/', views.update_events, name='update-event'),
      # path('delete_event/<int:id>/', views.delete_events, name='delete-event'),
]

soul_connection_dashboard/soul_connection_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from admin_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employees/', include("admin_app.urls", namespace="admin_app")),
    path('coachs/', include("coach.urls", namespace="coachs")), 
    path('customers/', include("customer.urls", namespace="customers")),
    path('encounters/', include("encounters.urls", namespace="encounters")),
    path('tips/', include("tips.urls", namespace="tips")),
    path('events/', include("events.urls", namespace="events")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

soul_connection_dashboard/tips/urls.py
from django.urls import path
from . import views

app_name = "tips"

urlpatterns = [
     path('list/', views.list_tips, name='tips-list'),
]

soul_connection_dashboard/events/models.py
from django.db import models
from coach.models import Employee


class Event(models.Model):
    def __str__(self):
        return f'{self.id} - {self.name}- {self.date}- {self.duration}'
    id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=500)
    date = models.CharField(max_length=5000)
    duration = models.IntegerField()
    max_participants = models.IntegerField()
    location_x = models.CharField(max_length=500)
    location_y = models.CharField(max_length=500)
    type = models.CharField(max_length=500)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='encounters')
    location_name = models.CharField(max_length=500)

soul_connection_dashboard/events/forms.py
from django import forms
from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = "__all__"

soul_connection_dashboard/events/views.py
from django.shortcuts import render

# Create your views here.
from .models import Event
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse
from .forms import EventForm
from django.contrib.auth.decorators import login_required, permission_required

@login_required(login_url='/employees/login')
def list_event(request):
    events = Event.objects.all()
    event_tab = []
    for i in events:
        event_tab.append(i)
    return render(request, 'events/list_events.html', {'event_tab': event_tab})

@login_required(login_url='/employees/login')
def create_events(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('events:event-list')
        else:
             print("Les erreurs :", form.errors)
    else:
        form = EventForm()
    return render(request,'events/create_events.html',{'form': form})

@login_required(login_url='/employees/login')
def update_events(request, id):
    events = Event.objects.get(id=id)
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES, instance=events)
        if form.is_valid():
            events = form.save()
            return redirect('events:event-list')
    else:
        form = EventForm(instance=events)
    return render(request,'events/update_events.html',{'form': form, 'events': events})

# @login_required(login_url='/employees/login')
# @permission_required("", login_url="")
# def delete_events(request, id):
#     events = Event.objects.get(id=id)
#     if request.method == 'POST':
#         if events.location_name:
#             events.delete()
#         events.delete()
#         return redirect('events:event-list')
#     return render(request,'events/delete_events.html',{'events': events})

soul_connection_dashboard/events/templates/events/create_events.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Créer un Evenement</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_employee.css' %}">
</head>

<body>
    {% block content %}
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}">Coaches</a>
            <a href="{% url 'customers:customer' %}">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}"class="active">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>
    <div class="form-container">
        <h1>Create Event</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <div class="input-field">
                    <label for="id">Event id:</label>
                    {{ form.id }}
                </div>
                <div class="input-field">
                    <label for="name">Event name</label>
                    {{ form.name }}
                </div>
                <div class="input-field">
                    <label for="date">Event date:</label>
                    {{ form.date }}
                </div>
                <div class="input-field">
                    <label for="duration">Event duration:</label>
                    {{ form.duration }}
                </div>
                <div class="input-field">
                    <label for="max_participants">Max participants:</label>
                    {{ form.max_participants }}
                </div>
                <div class="input-field">
                    <label for="location_x">Location x:</label>
                    {{ form.location_x }}
                </div>
                <div class="input-field">
                    <label for="location_y">Location y:</label>
                    {{ form.location_y }}
                </div>
                <div class="input-field">
                    <label for="type">Type:</label>
                    {{ form.type }}
                </div>
                <div class="input-field">
                    <label for="employee">Employee:</label>
                    {{ form.employee }}
                </div>
                <div class="input-field">
                    <label for="location_name">Location name:</label>
                    {{ form.location_name }}
                </div>
            </div>
            <button type="submit" class="btn-submit">Create</button>
        </form>
    </div>
    {% endblock %}
</body>

</html>

soul_connection_dashboard/events/templates/events/delete_events.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete an event</title>
</head>
<body>

</body>
</html>

soul_connection_dashboard/events/templates/events/list_events.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive calendar</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_event.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
</head>

<body>
{% block content %}
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}">Coaches</a>
            <a href="{% url 'customers:customer' %}">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}" class="active">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>
    <div class="header">
        <h1>Events</h1>
        <a href="{% url 'events:event-create' %}">
            <button class="add-button">+ Add Event</button>
        </a>
        <button type="button" id="cancelDelete" class="back-button"><span>&larr;</span>Back</button>
    </div>

    <table class="customer-table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Date</th>
        <th>Duration</th>
        <th>max_participants</th>
        <th>location_x</th>
        <th>location_y</th>
        <th>type</th>
        <th>employee</th>
        <th>location_name</th>
    </tr>
    </thead>
    <tbody>
    {% for cus in event_tab %}
        <tr>
            <td>
                {{ cus.id }}
            </td>
            <td>
                <a href="{% url 'events:update-event' cus.id %}"
                   style="text-decoration:none; color:#063666; font-weight:bold;">{{ cus.name }}</a>
            </td>
            <td>{{ cus.date }}</td>
            <td>{{ cus.duration }}</td>
            <td>{{ cus.max_participants }}</td>
            <td>{{ cus.location_x }}</td>
            <td>{{ cus.location_y }}</td>
            <td>{{ cus.type }}</td>
            <td>{{ cus.employee }}</td>
            <td>{{ cus.location_name }}</td>
        </tr>
        </tbody>
    {% endfor %}
    </table>

    <div id="calendar" style="margin-top: 100px"></div>
    <div id="eventModal" style="display:none;">
        <label for="eventTitleInput">
            <input type="text" id="eventTitleInput" placeholder="Enter new event title">
        </label>
        <button id="saveEventTitle">Save</button>
    </div>
    <script>
        var selectedEvent = null;

        function getRandomClass() {
            const classes = ['random-color-1', 'random-color-2', 'random-color-3', 'random-text-color'];
            return classes[Math.floor(Math.random() * classes.length)];
        }

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                headerToolbar: {
                    left: 'title prev,next',
                    center: '',
                    right: 'today dayGridMonth,timeGridWeek,timeGridDay'
                },
                events: async function (fetchInfo, successCallback, failureCallback) {
                    try {
                        const response = await fetch('/events/list/');
                        const data = await response.json();

                        const events = data.map(event => ({
                            title: event.title,
                            start: event.start,
                            end: event.end,
                            className: getRandomClass()
                        }));

                        successCallback(events);
                    } catch (error) {
                        console.error('Error while collecting events data:', error);
                        failureCallback(error);
                    }
                },
                eventClick: function (info) {
                    selectedEvent = info.event;
                    document.getElementById('eventTitleInput').value = selectedEvent.title;
                    document.getElementById('eventModal').style.display = 'block';
                }
            });
            calendar.render();
        });

        document.getElementById('saveEventTitle').addEventListener('click', function () {
            if (selectedEvent) {
                var newTitle = document.getElementById('eventTitleInput').value;
                selectedEvent.setProp('title', newTitle);
                document.getElementById('eventModal').style.display = 'none';
            }
        });
    </script>
{% endblock %}
</body>

</html>

soul_connection_dashboard/events/templates/events/update_events.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update event page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_employee.css' %}">
</head>

<body>
    {% block content %}
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}">Coaches</a>
            <a href="{% url 'customers:customer' %}">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}"class="active">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>
    <div class="form-container">
        <h1>Update Event</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <div class="input-field">
                    <label for="id">Event id:</label>
                    {{ form.id }}
                </div>
                <div class="input-field">
                    <label for="name">Event name</label>
                    {{ form.name }}
                </div>
                <div class="input-field">
                    <label for="date">Event date:</label>
                    {{ form.date }}
                </div>
                <div class="input-field">
                    <label for="duration">Event duration:</label>
                    {{ form.duration }}
                </div>
                <div class="input-field">
                    <label for="max_participants">Max participants:</label>
                    {{ form.max_participants }}
                </div>
                <div class="input-field">
                    <label for="location_x">Location x:</label>
                    {{ form.location_x }}
                </div>
                <div class="input-field">
                    <label for="location_y">Location y:</label>
                    {{ form.location_y }}
                </div>
                <div class="input-field">
                    <label for="type">Type:</label>
                    {{ form.type }}
                </div>
                <div class="input-field">
                    <label for="employee">Employee:</label>
                    {{ form.employee }}
                </div>
                <div class="input-field">
                    <label for="location_name">Location name:</label>
                    {{ form.location_name }}
                </div>
            </div>
            <button type="submit" class="btn-submit">Create</button>
        </form>
    </div>
    {% endblock %}
</body>

</html>