soul_connection_dashboard/admin_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "admin_app"

urlpatterns = [
    path('login/', views.login_employee, name='login'),
    path('logout/', views.logout_employee, name='logout'),
    path('dash/', views.acceuil, name='dash'),  # Page d'accueil
    #path('customer/<int:customer_id>/', views.customer_details, name='customer_details'),
]

soul_connection_dashboard/coach/urls.py
from django.urls import path
from .views import list_employees
from . import views

app_name = "coachs"

urlpatterns = [
    path('list/', views.list_employees, name='coach'),
    path('create/', views.create_employee, name='coach-create'),
    path('detail/<int:id>/', views.detail_employee, name='coach-detail'),
    path('detail/<int:id>/message', views.create_message, name='message-create'),
    path('detail/<int:id>/messages/list', views.list_messages, name='message-list'),
    path('update/<int:id>/', views.update_employee, name='coach-update'),
    path('delete/<int:id>/', views.delete_employee, name='coach-delete'),
    #path('customer/<int:customer_id>/', views.customer_details, name='customer_details'),
]

soul_connection_dashboard/customer/urls.py
from django.urls import path
from .views import list_customers
from . import views

app_name = "customers"

urlpatterns = [
    path('list/', views.list_customers, name='customer'),
    path('compatibility/', views.customers_compatibility, name='compatibility'),
    path('create/', views.create_customers, name='customer-create'),
    path('detail/<int:id>/', views.detail_customers, name='customer-detail'),
    path('<int:id>/clothes/', views.customers_clothes, name='customer-clothes'),
    path('update/<int:id>/', views.update_customers, name='customer-update'),
    path('delete/<int:id>/', views.delete_customers, name='customer-delete'),
    path('<int:id>/clothes/create_clothes/', views.create_clothe, name='customer-create-clothes'),
    path('<int:customer_id>/clothes/update_clothes/<int:id>/', views.update_clothe, name='customer-update-clothes'),
    path('<int:customer_id>/clothes/delete_clothes/<int:id>', views.delete_clothe, name='customer-delete-clothes'),
]

soul_connection_dashboard/events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
      path('list/', views.list_event, name='event-list'),
      path('create_event/', views.create_events, name='event-create'),
      path('update_event/<int:id>/', views.update_events, name='update-event'),
      # path('delete_event/<int:id>/', views.delete_events, name='delete-event'),
]

soul_connection_dashboard/soul_connection_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from admin_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employees/', include("admin_app.urls", namespace="admin_app")),
    path('coachs/', include("coach.urls", namespace="coachs")), 
    path('customers/', include("customer.urls", namespace="customers")),
    path('encounters/', include("encounters.urls", namespace="encounters")),
    path('tips/', include("tips.urls", namespace="tips")),
    path('events/', include("events.urls", namespace="events")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

soul_connection_dashboard/tips/urls.py
from django.urls import path
from . import views

app_name = "tips"

urlpatterns = [
     path('list/', views.list_tips, name='tips-list'),
]

soul_connection_dashboard/coach/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

class EmployeeManager(BaseUserManager):
    def create_employee(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_employee(email, password, **extra_fields)

class Employee(AbstractBaseUser, PermissionsMixin):
    def __str__(self):
        return f'{self.id} - {self.name} - {self.surname} - {self.email}'
    id = models.IntegerField(unique=True, primary_key=True)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=128, default="1234")
    birth_date = models.CharField(max_length=1000, blank=True)
    gender = models.CharField(max_length=100)
    work = models.CharField(max_length=100)
    image = models.ImageField(upload_to='employees_image/')
    address = models.CharField(max_length=100, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    
    last_login = models.DateTimeField(blank=True, null=True)
    groups = models.ManyToManyField('auth.Group', related_name='employee_set',blank=True)
    user_permissions = models.ManyToManyField('auth.Permission', related_name='employee_permissions_set', blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = EmployeeManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'surname']

class Message(models.Model):
    def __str__(self):
        return f'{self.sender} - {self.receiver}'
    sender = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='receiver')
    content = models.TextField(max_length=50000)

soul_connection_dashboard/coach/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Employee, Message

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['id', 'name', 'surname', 'email', 'password','birth_date', 'gender', 'work', 'image', 'address', 'phone_number']
        widgets = {
            'password': forms.PasswordInput()
        }

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['sender'].queryset = Employee.objects.filter(work="Coach")
        self.fields['receiver'].queryset = Employee.objects.filter(work="Coach")

class CustomUserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'date_joined', 'password']

    email = forms.EmailField(label='E-mail', required=True)
    first_name = forms.CharField(label='Nom', required=True)
    last_name = forms.CharField(label='Prénom', required=True)
    date_naissance = forms.DateField(label='Date de Naissance', required=True)
    genre = forms.ChoiceField(choices=[('masculin', 'Masculin'), ('feminin', 'Féminin'), ('autre', 'Autre')], label='Genre', required=True)
    password = forms.CharField(widget=forms.PasswordInput(), label='Mot de Passe', required=True)
    phone = forms.CharField(label='Numéro de Téléphone', required=True)
    adresse = forms.CharField(label='Adresse', required=True)
    work = forms.CharField(widget=forms.Textarea, label='Travail', required=False)
    image = forms.ImageField(label='Image', required=True)

soul_connection_dashboard/coach/views.py
# Create your views here.
from django.shortcuts import render
from .models import Employee, Message
from .forms import EmployeeForm, MessageForm
from django.shortcuts import redirect
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required(login_url='/employees/login/')
def create_employee(request):
    messages_error = ""
    if request.method == 'POST':
        form = EmployeeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('coachs:coach-detail', id=form.instance.id)
        else:
            messages_error = "Form is not valid"
            print("Les erreurs :", form.errors)
    else:
        form = EmployeeForm()
    return render(request,
                  'employee/create_employee.html',
                  {'form': form, 'messages_error': messages_error})

@login_required(login_url='/employees/login/')
def list_employees(request):
    employees = Employee.objects.all()
    if request.method == "GET":
        name = request.GET.get('name')
        surname = request.GET.get('surname')

        if name or surname:
            employees = Employee.objects.filter(name=name, surname=surname)

    coaches = Employee.objects.filter(work="Coach")
    nbr_coach = coaches.count()
    return render(request,'employee/list_employees.html',{'employees': employees, 'coaches': coaches, 'nbr_coach': nbr_coach})

@login_required(login_url='/employees/login/')
def detail_employee(request, id):
    employee = Employee.objects.get(id=id)
    customers = employee.clients.all()
    return render(request,
                  'employee/detail_employee.html',
                  {'employee': employee,
                   'customers': customers
                   })

@login_required(login_url='/employees/login/')
def update_employee(request, id):
    employee = Employee.objects.get(id=id)
    if request.method == 'POST':
        form = EmployeeForm(request.POST, request.FILES, instance=employee)
        if form.is_valid():
            employee = form.save()
            return redirect('coachs:coach-detail', id=employee.id)
    else:
        form = EmployeeForm(instance=employee)
    return render(request,
                  'employee/update_employee.html',
                  {'form': form, 'employee': employee})

@login_required(login_url='/employees/login/')
def delete_employee(request, id):
    employee = Employee.objects.get(id=id)
    if request.method == 'POST':
        if employee.image:
            employee.image.delete()
        employee.delete()
        return redirect('coachs:coach')
    return render(request,
                  'employee/delete_employee.html',
                  {'employee': employee})

@login_required(login_url='/employees/login/')
def create_message(request, id):
    messages_error = ""
    employee = Employee.objects.get(id=id)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('coachs:message-list', id=employee.id)
        else:
            messages_error = "Form is not valid"
            print("Les erreurs :", form.errors)
    else:
        form = MessageForm()
    return render(request,
                  'employee/create_message.html',
                  {'form': form, 'messages_error': messages_error})

@login_required(login_url='/employees/login/')
def list_messages(request, id):
    employee = Employee.objects.get(id=id)
    my_messages = Message.objects.filter(receiver=employee)
    return render(request,
                  'employee/list_message.html',
                  {'my_messages': my_messages}) 


# def form(request):
#     if request.method == 'POST':
#         form = CustomUserCreationForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             messages.success(request, "Employé créé avec succès !")
#             return redirect('connexion')
#         else:
#             messages.error(request, "Erreur lors de la création de l'employé.")
#     else:
#         form = CustomUserCreationForm()
#     return render(request, 'form.html', {'form': form})

soul_connection_dashboard/coach/templates/employee/create_employee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Créer un Employé</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_employee.css' %}">
</head>
<body>
    {% block content %}
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}" class="active">Coaches</a>
            <a href="{% url 'customers:customer' %}">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>
    <div class="form-container">
        <h1>Create Employee</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <div class="form-group">
                <div class="input-field">
                    <label for="id">ID:</label>
                    {{form.id}}
                </div>
                <div class="input-field">
                    <label for="name">Name:</label>
                    {{form.name}}
                </div>

                <div class="input-field">
                    <label for="surname">Surname:</label>
                    {{form.surname}}
                </div>

                <div class="input-field">
                    <label for="email">E-mail:</label>
                    {{form.email}}
                </div>

                <div class="input-field">
                    <label for="password">Password:</label>
                    <input type="password" id="password" name="password">
                    <span id="togglePassword" onclick="togglePassword()" style="cursor: pointer; color: blue; text-decoration: underline;">Show Password</span>
                </div>

                <div class="input-field">
                    <label for="birth_date">Birth Date:</label>
                    {{form.birth_date}}
                </div>

                <div class="input-field">
                    <label for="gender">Gender:</label>
                    {{form.gender}}
                </div>

                <div class="input-field">
                    <label for="work">Work:</label>
                    {{form.work}}
                </div>

                <div class="input-field">
                    <label for="image">Image:</label>
                    {{form.image}}
                </div>

                <div class="input-field">
                    <label for="address">Adress:</label>
                    {{form.address}}
                </div>

                <div class="input-field">
                    <label for="phone_number">Phone number:</label>
                    {{form.phone_number}}
                </div>
            </div>
            <button type="submit" class="btn-submit">Create</button>
        </form>
        {{messages_error}}
    </div>

    <script>
        function togglePassword() {
            var passwordField = document.getElementById("password");
            var toggleText = document.getElementById("togglePassword");
    
            if (passwordField.type === "password") {
                passwordField.type = "text";
                toggleText.textContent = "Hide Password";  // Change le texte en "Hide Password"
            } else {
                passwordField.type = "password";
                toggleText.textContent = "Show Password";  // Remet le texte en "Show Password"
            }
        }
    </script>
    
    {% endblock %}
</body>
</html>

soul_connection_dashboard/coach/templates/employee/delete_employee.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Suppression d'utilisateur</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_del_emp.css' %}">
</head>

<body>
    {% block content %}
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}"class="active">Coaches</a>
            <a href="{% url 'customers:customer' %}">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>

    <button class="back-button" onclick="history.back()">Back</button>

    <div class="container home">
        <div class="confirmation-box">
            <p>Do you really want to delete {{employee.name}} {{employee.surname}} ?</p>
            <form method="POST" action="{% url 'coachs:coach-delete' employee.id %}">
                {% csrf_token %}
                <button type="submit" class="confirm-button">Confirm</button>
                <button type="button" id="cancelDelete" class="cancel-button">Cancel</button>
            </form>

            <div class="delete-message" id="deleteMessage" style="display: none;">This user has been deleted.</div>
        </div>
    </div>

    <script>
        // Gestion du bouton "Annuler"
        document.getElementById("cancelDelete").onclick = function () {
            history.back();
        }

        // Simuler un message de confirmation de suppression si le formulaire est soumis
        document.querySelector("form").onsubmit = function (event) {
            event.preventDefault();

            // Simuler la suppression
            var deleteMessage = document.getElementById("deleteMessage");
            deleteMessage.style.display = "block";

            setTimeout(function () {
                event.target.submit();
            }, 2000);
        }
    </script>
    {% endblock %}
</body>
</html>

soul_connection_dashboard/coach/templates/employee/detail_employee.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer details</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_detail_emplo.css' %}">
</head>
<body>
    {% block content %}
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}"class="active">Coaches</a>
            <a href="{% url 'customers:customer' %}">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="globe">🌍</div>
            <div class="icon2">👤</div>
        </div>
    </div>
    <!-- Header with Title and Back Button -->
    <div class="header">
        <h1>Coach Details</h1>
        <button type="button" id="cancelDelete" class="back-button"><span>&larr;</span>Back</button>
    </div>
    <div class="container">
        <!-- Left Pane -->
        <div class="left-pane-box">
            <div class="left-pane">
                <div class="user-info">
                    <img src="{{ employee.image.url }}" alt="User Photo">
                    <h2>{{ employee.name }} {{ employee.surname }}</h2>
                </div>
                <div class="icone">
                    <p><i class="fas fa-envelope"></i></p>
                </div>
                <div class="short-details">
                    <div class="detail-item">
                        <strong>User ID</strong>
                        <p>{{ employee.id }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Email</strong>
                        <p>{{ employee.email }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Address</strong>
                        <p>{{ employee.address }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Last Activity</strong>
                        <p>{{ employee.last_login }}</p>
                    </div>
                    <div class="detail-item">
                        <strong>Number of customers</strong>
                        <p>{{ customers|length }}</p>
                    </div>
                    <div class="mes-buttons">
                        <a href="{% url 'coachs:message-create' employee.id %}" class="chat-button">Message</a>
                        <a href="{% url 'coachs:message-list' employee.id %}" class="inb-button">Inbox</a>
                    </div>
                    <div class="mod-buttons">
                        <a href="{% url 'coachs:coach-update' employee.id %}" class="edit-button">Edit</a>
                        <a href="{% url 'coachs:coach-delete' employee.id %}" class="delete-button">Delete</a>
                    </div>
                    {% if user.is_authenticated %}
                        <br> <a href="{% url 'admin_app:logout' %}">Se déconnecter</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="right-pane">
            <table class="coach-table">
                <thead>
                    <tr>
                        <th>Customers</th>
                        <th>Email</th>
                        <th>Phone</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cus in customers %}
                    <tr>
                        <td class="checkbox-customer">
                            <input type="checkbox" name="select_customer" value="{{ cus.id }}">
                            <div class="customer-name">
                                <div class="initial-circle" data-initials="{{ customer.name|slice:" :1" }}{{
                                    customer.surname|slice:":1" }}">
                                    {{ cus.name|slice:":1" }}{{ cus.surname|slice:":1" }}
                                </div>
                                <a href="{% url 'customers:customer-detail' cus.id%}">{{ cus.name }} {{ cus.surname }}</a>
                            </div>
                        </td>
                        <td>{{ cus.email }}</td>
                        <td>{{ cus.phone_number}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script>
        function getRandomColor() {
            const letters = '0123456789ABCDEF';
            let color = '#';
            for (let i = 0; i < 6; i++) {
                color += letters[Math.floor(Math.random() * 16)];
            }
            return color;
        }

        document.querySelectorAll('.initial-circle').forEach(circle => {
            circle.style.backgroundColor = getRandomColor();
        });

        document.getElementById("cancelDelete").onclick = function () {
            history.back();
        }
    </script>
    {% endblock %}
</body>
</html>

soul_connection_dashboard/coach/templates/employee/list_employees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Coaches List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        .navbar {
            background-color: #fff;
            padding: 10px 20px;
            border-bottom: 1px solid #ddd;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .navbar a {
            text-decoration: none;
            color: #333;
            margin-right: 20px;
            font-weight: bold;
            position: relative;
        }

        .navbar a.active {
            color: #007bff;
        }

        .navbar a.active::after {
            content: '';
            position: absolute;
            bottom: -10px;
            left: 0;
            width: 100%;
            height: 5px;
            border-radius: 3px;
            background-color: #007bff;
        }

        .navbar .logo {
            font-size: 20px;
            font-weight: bold;
            color: #333;
        }

        .navbar .right-icons {
            display: flex;
            align-items: center;
        }

        .navbar .icon {
            margin-left: 25px;
        }

        .container {
            max-width: 1800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .coach-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .coach-table th, .coach-table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .coach-table th {
            background-color: #f2f2f2;
        }

        .coach-table tbody tr:hover {
            background-color: #f1f1f1;
        }

        .initial-circle {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            text-align: center;
            line-height: 40px;
            font-weight: bold;
            color: #fff;
            margin-right: 10px;
            display: inline-block;
        }

        .coach-name {
            display: flex;
            align-items: center;
        }

        .coach-name a {
            text-decoration: none;
            color: #063666;
            font-weight: bold;
        }

        .coach-name a:hover {
            text-decoration: none;
        }

        .action-button {
            border: none;
            background: none;
            cursor: pointer;
        }

        .action-button .dots {
            font-size: 18px;
        }

        .checkbox-coach {
            display: flex;
            align-items: center;
        }

        .checkbox-coach input[type="checkbox"] {
            margin-right: 10px;
        }

        .button-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .button-left {
            display: flex;
            gap: 10px;
        }

        .button-right {
            display: flex;
            gap: 10px;
        }

        .button-left button, .button-right button {
            padding: 10px 20px;
            font-size: 16px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .button-left button {
            background-color: #007bff;
            color: white;
        }

        .button-right button {
            background-color: #1ee01e;
            color: white;
        }

        .button-right button:last-child {
            background-color: #007bff;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <div class="logo">Soul Connection</div>
        <div>
            <a href="{% url 'admin_app:dash' %}">Dashboard</a>
            <a href="{% url 'coachs:coach' %}" class="active">Coaches</a>
            <a href="{% url 'customers:customer' %}">Customers</a>
            <a href="{% url 'tips:tips-list' %}">Tips</a>
            <a href="{% url 'events:event-list' %}">Events</a>
            <a href="{% url 'customers:compatibility' %}">Compatibility</a>
        </div>
        <div class="right-icons">
            <div class="icon">🌍</div>
            <div class="icon">👤</div>
        </div>
    </div>
    <div class="container">
        <h1>Coaches List</h1>
        <p>You have a total of {{nbr_coach}} coaches.</p>
        <form class="d-flex" style="margin-bottom: 20px">
            <input class="form-control me-2" type="search" name="name" placeholder="Nom" aria-label="Nom">
            <input class="form-control me-2" type="search" name="surname" placeholder="Prénom" aria-label="Prénom">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <div class="button-container">
            <div class="button-left">
                <button>Bulk Action</button>
                <button>Apply</button>
            </div>
            <div class="button-right">
                <a href="{% url 'coachs:coach-create' %}">
                    <button style="background-color: #1fd828; color: white;">Add+</button>
                </a>
                <button>Export</button>
            </div>
        </div>

        <table class="coach-table">
            <thead>
                <tr>
                    <th><input type="checkbox" id="select_all" /> Coach</th>                    
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Number of customers</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for coach in coaches %}
                <tr>
                    <td class="coach-name">
                        <input type="checkbox" name="select_coach" value="{{ coach.id }}" class="checkbox-coach">
                        <div class="initial-circle" data-initials="{{ coach.name|slice:":1" }}{{ coach.surname|slice:":1" }}">
                            {{ coach.name|slice:":1" }}{{ coach.surname|slice:":1" }}
                        </div>
                        <a href="{% url 'coachs:coach-detail' coach.id %}">{{ coach.name }} {{ coach.surname }}</a>
                    </td>
                    <td>{{ coach.email }}</td>
                    <td>{{ coach.phone_number }}</td>
                    <td>{{ coach.clients.count }}</td>
                    <td>
                        <button class="action-button">
                            <span class="dots">...</span>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script>
        document.getElementById('select_all').addEventListener('click', function () {
            const checkboxes = document.querySelectorAll('input[name="select_coach"]');
            checkboxes.forEach(checkbox => checkbox.checked = this.checked);
        });

        function getRandomColor() {
            const letters = '0123456789ABCDEF';
            let color = '#';
            for (let i = 0; i < 6; i++) {
                color += letters[Math.floor(Math.random() * 16)];
            }
            return color;
        }

        document.querySelectorAll('.initial-circle').forEach(circle => {
            circle.style.backgroundColor = getRandomColor();
        });
    </script>
</body>
</html>